function [] = WriteMat(unit_cell_type, wavelength_band, units, data_format, varargin)
    
    % unit_cell_type;  % string % Type of unit cell (circle, square, etc.)
    unit_cell_type = char(unit_cell_type);
                                % Standard names: [circle, square, ellipse, rectangle, cross, circle_coat, circle_embed]
    % wavelength_band; % string % Name of wavelength band ('visible', 'MIR', etc.)
    wavelength_band = char(wavelength_band);
                                % Standard names: [UV, visible, NIR, SWIR, MWIR, LWIR, MIR, FIR, visible_[roygbv]]
    % units;           % string % Units for dimensions, or "normal"
    units = char(units);
    data_format = char(data_format); % 'RealImag' or 'AmpPhase'

    array_type = 'square';        % Type of array (square or hexagonal)
    dispersion_flag = false;      % If any materials are dispersive,
                                  % will automatically set to true.

    material_names = {}; % String array of names of each material
                                 % Standard: Use chemical symbol notation when possible (i.e. Si, Al2O3, etc).
    material_use   = {};         % Where material is used
                                 % Standard names: [substrate, pillar, background, coating]
    material_index = {};         % Refractive index of each parameter
    material_notes = {}; % Notes on material (data source citation recommended)
    material_dispersion_flag = logical([]); % Bool array,
                    % Automatically set based on length of material index input.
                    % If dispersion_flag is true, material is dispersive
                    % and thus index is specified at every wavelength.
    m_num = 0;                   % Counter for number of materials

    param_names = {};  % String array of names of each variable parameter
                               % First parameter should always be "wavelength"
                               % Additional names: circle: [diameter]
                               %                   square: [width]
                               %                   ellipse: [width_x, width_y]
                               %                   rectangle: [width_x, width_y]
                               %                   cross: [width, aspect_ratio]
    param_values = {};         % Preferred: Limits of each parameter, [min, max, num_of_values]
                               % Alternate: List of parameter values
    param_notes = {};  % String array of notes for each parameter
    p_num = 0;                 % Counter for number of parameters

    constant_names = {};  % String array of names of each constant
                                  % Standard names: [height, pitch, thickness]
                                  % If units = "normal", don't specify pitch
                                  % Thickness is only for meta-atoms with coatings
    constant_values = {};         % Values of each constant
    constant_notes = {};  % String array of notes for each constant
    c_num = 0;                    % Counter for number of constants

    data_names = {};  % String array of names for each data matrix
                              % Standard names: [field1_field2_polar_suffix]
                              %         field1 = [transmission or reflection]
                              %         field2 = [bottom or top]
                              %         polar = [Ex or Ey]
                              %         suffix is optional, but can be used to denote diffraction order [e.g. 0_1]
    data_values = {};         % cell array containing each data matrix
    data_notes = {};  % String array of notes for each data matrix
    d_num = 0;                % Counter for number of data matrices

    creator = '';     % Name of person who generated the file
    date = char(datetime("today","format","yyyy-MM-dd")); % Date file was generated
    notes = '';       % Any other notes about the file (special simulation settings, name of generating script, etc.)

    % File name and save directory will default to an autogenerated name
    % and default save location, unless specified
    filename = [];             % File name for created file.
    save_dir = "Library Data"; % Location to save file

    %% parse optional input parameters
    i = 1;
    while i < numel(varargin)
        switch varargin{i}
            case 'Array' % Shape of array (square or hexagonal)
                array_type = char(varargin{i+1});
                if ~strcmp(array_type, 'square') && ~strcmp(array_type, 'hexagonal')
                    warning('Unexpected array type: %s\nExpected ''square'' or ''hexagonal''', array_type)
                end
                i = i+2;
            case 'Material' % Four inputs: name, use, refractive_index, notes
                num_entry = length(varargin{i+2});

                material_names(m_num + (1:num_entry)) = {char(varargin{i+1})};
                if num_entry == 1
                    material_use(m_num + 1) = {char(varargin{i+2})};
                else
                    material_use(m_num + (1:num_entry)) = convertStringsToChars(varargin{i+2});
                end
                for j = 1:num_entry
                    material_index{m_num + j} = varargin{i+3};
                end
                material_notes(m_num + (1:num_entry)) = {char(varargin{i+4})};

                if isscalar(varargin{i+3})
                    material_dispersion_flag(m_num + (1:num_entry)) = false;
                else
                    material_dispersion_flag(m_num + (1:num_entry)) = true;
                    dispersion_flag = true;
                end
                m_num = m_num + num_entry;
                i = i+5;
            case 'Param' % Three inputs: name, values, notes
                p_num = p_num + 1;
                param_names{p_num} = char(varargin{i+1});
                param_values{p_num} = varargin{i+2};
                param_notes{p_num} = char(varargin{i+3});
                i = i+4;
            case 'Constant' % Three inputs: name, value, notes
                c_num = c_num + 1;
                constant_names{c_num} = char(varargin{i+1});
                constant_values{c_num} = varargin{i+2};
                constant_notes{c_num} = char(varargin{i+3});
                i = i+4;
            case 'Data' % Three inputs: name, value, notes
                d_num = d_num + 1;
                data_names{d_num} = char(varargin{i+1});
                data_values{d_num} = varargin{i+2};
                data_notes{d_num} = char(varargin{i+3});
                i = i+4;
            case 'Creator' % One input: Name of person creating data file
                creator = char(varargin{i+1});
                i = i+2;
            case 'Date' % One input: Date data was generated
                date = char(varargin{i+1});
                i = i+2;
            case 'Notes'
                notes = char(varargin{i+1});
                i = i+2;
            case 'Filename'
                filename = string(varargin{i+1});
                i = i+2;
            case 'SaveDirectory'
                save_dir = string(varargin{i+1});
                i = i+2;
            otherwise
                error("Unsupported parameter: %s\nin field %d", varargin{i}, i+2);
        end
    end

    %% Go to Data folder
    if ~exist(save_dir, "dir")
        warning("Directory %s not found. Creating directory.", save_dir)
        mkdir(save_dir)
    end
    DataFolder = what(save_dir);
    PrevFolder = cd(DataFolder(1).path);
    
    %% Generated file name, if not manually named
    if isempty(filename)
        isheight = strcmpi(constant_names, "height");
        if any(isheight)
            height = constant_values{isheight};
        else
            error(['To use the automatic naming convention, you must specify the\n' ...
                'unit cell height as a constant using the input format:\n' ...
                '"Constant", "height", #val#, "%notes%"'])
        end
        
        issubstrate = strcmpi(material_use, "substrate");
        if any(issubstrate)
            substrate_material = material_names{issubstrate};
        else
            error(['To use the automatic naming convention, you must specify the substrate material:' ...
                '"Material", "%MaterialName%", "substrate", #index#, "%notes%"'])
        end

        ispillar = strcmpi(material_use, "pillar");
        if any(ispillar)
            pillar_material = material_names{ispillar};
        else
            error(['To use the automatic naming convention, you must specify the pillar material:' ...
                '"Material", "%MaterialName%", "pillar", #index#, "%notes%"'])
        end

        %Create File Name
        if strcmpi(units,"normal")
            filename = sprintf('%s_%s_on_%s_%s_H%04.0f_', wavelength_band, pillar_material, substrate_material, unit_cell_type, 100*height);
        else
            filename = sprintf('%s_%s_on_%s_%s_H%04.3g%s_', wavelength_band, pillar_material, substrate_material, unit_cell_type, height, units);
            filename = strrep(filename, '.', 'p');
        end

        % Check for duplicate names, and add trailing digit to make unique name
        try
            conflictNames = string(ls([filename '*']));
            existingNums = double(string(extractBetween(conflictNames,filename,'.mat')));
            num = 0;
            while any(existingNums == num)
                num = num+1;
            end
        catch
            num = 0;
        end
        filename = [filename sprintf('%d.mat',num)];
    end
    
    %% Various warnings
    if dispersion_flag && strcmpi(units, "normal")
        warning("It looks like you're inputted a dispersive material,\n" + ...
            "but you've set the units to ""normal"".")
    end
    if ~dispersion_flag && ~strcmpi(units, "normal")
        warning("When saving data for non-dispersive materials, it is preferred" + ...
            " to normalize the lengths and set the units to ""normal"".")
    end
    if strcmpi(units, "normal") && (any(strcmpi(constant_names, "pitch")) || any(strcmpi(param_names, "pitch")))
        warning("You have set the units to ""normal"" and also specifed a value for pitch.\n" + ...
            "Setting units = ""normal"" implies values are normalized to pitch,\n" + ...
            "which would make your pitch variable redundant.\n" + ...
            "If you have used a different normalization, consider creating a new\n" + ...
            "standard units keyword to indicate your normalization approach,\n" + ...
            "and state how your variables are normalized in the notes.")
    end
    if ~strcmpi(units, "normal") && ~(any(strcmpi(constant_names, "pitch")) || any(strcmpi(param_names, "pitch")))
        warning("The units have been set, but you have not specified a value for the pitch.\n" + ...
            "Normally, the pitch is only excluded if the units are set to ""normal"".")
    end
    if any(strcmpi(param_names, "height"))
        warning("You have specified the height as a parameter.\n" + ...
            "The preferred format is to specify the height as a constant.\n" + ...
            "Data corresponding to structures with different heights can be stored in seperate files.")
    end

    %% Save variables to file
    
    save(filename, "unit_cell_type", "array_type", "creator", "date", ...
        "data_format", "wavelength_band", "units", "dispersion_flag", "notes", ...
        "material_names", "material_use", "material_index", "material_notes", "material_dispersion_flag",...
        "param_names", "param_values", "param_notes", ...
        "constant_names", "constant_values", "constant_notes", ...
        "data_names", "data_values", "data_notes")

    cd(PrevFolder)
end